### ISSUE TITLE
Sezione contatti

### ISSUE THREAD

**Issue by cortosconto** [cortosconto/cortosconto.github.io#7]
Lasciare la nostra mail cortosconto@writeme.com per collaborazione e più avanti per l'invio manoscritti. Già, dove la mettiamo? Secondo me nella homepage, in basso, centrale

**Comment by szingaro** [comment]
l'ho aggiunta dell'ultima modifica, ma non pubblicata, la trovi sotto `_pages`.
a proposito, **prima che ci arrestino** a causa di quello che ho scritto in quella pagina, *dacci un occhio*.
